# Generated by Django 5.0 on 2023-12-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='budget',
            field=models.IntegerField(null=True),
        ),
    ]
